//! OrbitDock Protocol
//!
//! Shared types for communication between OrbitDock server and clients.
//! These types are serialized as JSON over WebSocket.

use uuid::Uuid;

// Re-exports
pub mod client;
pub mod control_deck;
pub mod conversation_contracts;
pub mod diff_merge;
pub mod domain_events;
pub mod grouping;
pub mod provider_normalization;
pub mod server;
pub mod types;

pub use client::ClientMessage;
pub use control_deck::*;
pub use server::ServerMessage;
pub use types::*;

/// Prefix for OrbitDock-generated session IDs, distinguishing them from
/// provider SDK IDs (Claude CLI, Codex thread IDs) which are plain UUIDs.
pub const OD_ID_PREFIX: &str = "od-";
pub const HTTP_HEADER_SERVER_VERSION: &str = "X-OrbitDock-Server-Version";
pub const HTTP_HEADER_SERVER_COMPATIBILITY: &str = "X-OrbitDock-Server-Compatibility";
pub const HTTP_HEADER_COMPATIBLE: &str = "X-OrbitDock-Compatible";
pub const HTTP_HEADER_COMPATIBILITY_REASON: &str = "X-OrbitDock-Compatibility-Reason";
pub const HTTP_HEADER_COMPATIBILITY_MESSAGE: &str = "X-OrbitDock-Compatibility-Message";
pub const HTTP_HEADER_CLIENT_VERSION: &str = "X-OrbitDock-Client-Version";
pub const HTTP_HEADER_CLIENT_COMPATIBILITY: &str = "X-OrbitDock-Client-Compatibility";
pub const SERVER_COMPATIBILITY: &str = "server_authoritative_session_v1";
pub const CAPABILITY_DASHBOARD_PROJECTION_V1: &str = "dashboard_projection_v1";
pub const CAPABILITY_MISSIONS_PROJECTION_V1: &str = "missions_projection_v1";
pub const CAPABILITY_SESSION_DETAIL_SURFACE_V1: &str = "session_detail_surface_v1";
pub const CAPABILITY_SESSION_COMPOSER_SURFACE_V1: &str = "session_composer_surface_v1";
pub const CAPABILITY_CONTROL_DECK_SURFACE_V1: &str = "control_deck_surface_v1";
pub const CAPABILITY_CONVERSATION_SURFACE_V1: &str = "conversation_surface_v1";

/// Generate a new unique OrbitDock-owned ID with the `od-` prefix.
pub fn new_id() -> String {
  format!("{}{}", OD_ID_PREFIX, Uuid::new_v4())
}

/// Generate a new direct OrbitDock session ID.
///
/// This makes the session-identity boundary explicit at call sites instead of
/// relying on string conventions or provider-specific assumptions.
pub fn new_session_id() -> String {
  new_id()
}

/// Returns true if the given ID was generated by OrbitDock (has `od-` prefix).
pub fn is_orbitdock_id(id: &str) -> bool {
  id.starts_with(OD_ID_PREFIX)
}

/// Returns true if the given ID looks like a provider SDK session ID (no `od-` prefix, non-empty).
pub fn is_provider_id(id: &str) -> bool {
  !id.is_empty() && !id.starts_with(OD_ID_PREFIX)
}

/// A validated provider session ID (Claude SDK or Codex thread ID).
///
/// Construction rejects OrbitDock IDs (`od-` prefix) and empty strings,
/// making it impossible to accidentally pass an OrbitDock session ID where
/// a provider resume ID is expected.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ProviderSessionId(String);

impl ProviderSessionId {
  /// Create a new ProviderSessionId, returning None if the value is an
  /// OrbitDock ID or empty.
  pub fn new(id: impl Into<String>) -> Option<Self> {
    let id = id.into();
    if is_provider_id(&id) {
      Some(Self(id))
    } else {
      None
    }
  }

  /// Get the inner string value.
  pub fn as_str(&self) -> &str {
    &self.0
  }

  /// Consume and return the inner String.
  pub fn into_string(self) -> String {
    self.0
  }
}

impl std::fmt::Display for ProviderSessionId {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.write_str(&self.0)
  }
}

impl AsRef<str> for ProviderSessionId {
  fn as_ref(&self) -> &str {
    &self.0
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn new_id_has_od_prefix() {
    let id = new_id();
    assert!(id.starts_with("od-"), "expected od- prefix, got: {id}");
  }

  #[test]
  fn new_session_id_has_od_prefix() {
    let id = new_session_id();
    assert!(id.starts_with("od-"), "expected od- prefix, got: {id}");
  }

  #[test]
  fn is_orbitdock_id_classifies_correctly() {
    assert!(is_orbitdock_id("od-550e8400-e29b-41d4-a716-446655440000"));
    assert!(!is_orbitdock_id("550e8400-e29b-41d4-a716-446655440000"));
    assert!(!is_orbitdock_id(""));
  }

  #[test]
  fn is_provider_id_classifies_correctly() {
    assert!(is_provider_id("550e8400-e29b-41d4-a716-446655440000"));
    assert!(is_provider_id("some-thread-id"));
    assert!(!is_provider_id("od-550e8400-e29b-41d4-a716-446655440000"));
    assert!(!is_provider_id(""));
  }

  #[test]
  fn provider_session_id_rejects_od_prefix() {
    assert!(ProviderSessionId::new("od-abc123").is_none());
  }

  #[test]
  fn provider_session_id_rejects_empty() {
    assert!(ProviderSessionId::new("").is_none());
  }

  #[test]
  fn provider_session_id_accepts_plain_uuid() {
    let id = ProviderSessionId::new("550e8400-e29b-41d4-a716-446655440000");
    assert!(id.is_some());
    assert_eq!(id.unwrap().as_str(), "550e8400-e29b-41d4-a716-446655440000");
  }

  #[test]
  fn provider_session_id_display() {
    let id = ProviderSessionId::new("abc-123").unwrap();
    assert_eq!(format!("{id}"), "abc-123");
  }
}
